### ISSUE TITLE
Part 28 - Password Protecting with Sessions using PHP MySQL

### ISSUE THREAD

**Issue by JorgeBautista** [thedigicraft/Atom.CMS#155]
Hi fellow students, I see this issue has been adressed a number of times already but I don't see where my error is. I can't log in and I just get redirected to login.php; I believe my syntax is fine and the files are in the admin folder.
login.php file.

session_start();

include('../config/connection.php');

if($_POST) {
	
	$q = "SELECT * FROM users WHERE email = '$_POST[email]' AND password = SHA1('$_POST[password]')";
	$r = mysqli_query($dbc, $q);
	
	if(mysqli_num_rows($r) == 1) {
		
		$_SESSION['username'] = $_POST['email'];
		header('Location: index.php');
		
	}	
}

<?php //include(D_TEMPLATE.'/navigation.php'); ?>				
				
	<div class="container"> 
				
		<div class="row">
			
			<div class="col-md-4 col-md-offset-4">
						
				<div class="panel panel-primary">
				
					<div class="panel-heading">
						<strong>Login</strong>						
					</div>
					
					<div class="panel-body" 
					
						<form action="login.php" method="post" role="form">
							
						  <div class="form-group">
						    <label for="email">Email address</label>
						    <input type="email" class="form-control" id="email" name="email" placeholder="Enter email">
						  </div>
						  
						  <div class="form-group">
						    <label for="password">Password</label>
						    <input type="password" class="form-control" id="password" name="password" placeholder="Password">
						  </div>
						
								  
						  
						    	  
						  <button type="submit" class="btn btn-default">Submit</button> 
						  
						</form>
					
					</div>
					</div>
			
			</div>
		</div>
	</div>
		
		

	</div>

	<?php //include(D_TEMPLATE.'/footer.php'); ?>	
		
	<?php //if($debug == 1) { include('widgets/debug.php'); } ?>

And my index.php
<?php
session_start();
if(!isset($_SESSION['username'])) {
	header('Location: login.php');	
	}
?>

**Comment by creptor** [comment]
I can't seem to find it, probably tomorrow at the morning I'll see the error, but remember to always place the `session_start();` AT THE BEGGINING of each file, where you use `$_SESSION` of course.

Also, another error is that you're parsing the $_POST['email'] as any value, because you're not checking it before setting it to the session, leaving a possibility for the session to be empty, and redirecting to the login again...... which could be the issue.

**Comment by creptor** [comment]
I can't seem to find it, probably tomorrow at the morning I'll see the error, but remember to always place the `session_start();` AT THE BEGGINING of each file, where you use `$_SESSION` of course.

Also, another error is that you're parsing the $_POST['email'] as any value, because you're not checking it before setting it to the session, leaving a possibility for the session to be empty, and redirecting to the login again...... which could be the issue.

**Comment by creptor** [comment]
I can't seem to find it, probably tomorrow at the morning I'll see the error, but remember to always place the `session_start();` AT THE BEGGINING of each file, where you use `$_SESSION` of course.

Also, another error is that you're parsing the $_POST['email'] as any value, because you're not checking it before setting it to the session, leaving a possibility for the session to be empty, and redirecting to the login again...... which could be the issue.

**Comment by creptor** [comment]
I can't seem to find it, probably tomorrow at the morning I'll see the error, but remember to always place the `session_start();` AT THE BEGGINING of each file, where you use `$_SESSION` of course.

Also, another error is that you're parsing the $_POST['email'] as any value, because you're not checking it before setting it to the session, leaving a possibility for the session to be empty, and redirecting to the login again...... which could be the issue.

**Comment by creptor** [comment]
I have found no errors ;c , the code is correct, but that is assuming that in the first part you placed the `<?php` and closed it, because i had to add it myself. Here is an example:
```
<?php session_start();

include('../config/connection.php');

if($_POST) {

    $q = "SELECT * FROM users WHERE email = '$_POST[email]' AND password = SHA1('$_POST[password]')";
    $r = mysqli_query($dbc, $q);

    if(mysqli_num_rows($r) == 1) {

        $_SESSION['username'] = $_POST['email'];
        header('Location: index.php');

    }
}?>
<?php //include(D_TEMPLATE.'/navigation.php'); ?>
..........etc
```

**Comment by JorgeBautista** [comment]
yes, php tags are in place, comparing it with login.php|Atom.CMS-master the only difference I see with Alan's code is I didn't include the wrap div around the panel. Do you think that's the problem?

<?php 

session_start();

include('../config/connection.php');

if($_POST) {
	
	$q = "SELECT * FROM users WHERE email = '$_POST[email]' AND password = SHA1('$_POST[password]')";
	$r = mysqli_query($dbc, $q);
	
	if(mysqli_num_rows($r) == 1) {
		
		$_SESSION['username'] = $_POST['email'];
		header('Location: index.php');
		
	}	
}

 ?>

<!DOCTYPE html>
<html>
<head>
	
	<title>Admin Login</title>
<meta name="viewport" content="width=device-width, initial-scale=1">	
			
	<?php include('config/css.php'); ?>
	
	<?php include('config/js.php'); ?>	
		
</head>
	
<body>
		
	<?php //include(D_TEMPLATE.'/navigation.php'); ?>				
				
	<div class="container"> 
				
		<div class="row">
			
			<div class="col-md-4 col-md-offset-4">
						
				<div class="panel panel-primary">
				
					<div class="panel-heading">
						<strong>Login</strong>						
					</div>
					
					<div class="panel-body" 
					
						<form action="login.php" method="post" role="form">
							
						  <div class="form-group">
						    <label for="email">Email address</label>
						    <input type="email" class="form-control" id="email" name="email" placeholder="Enter email">
						  </div>
						  
						  <div class="form-group">
						    <label for="password">Password</label>
						    <input type="password" class="form-control" id="password" name="password" placeholder="Password">
						  </div>
						
								  
						  
						    	  
						  <button type="submit" class="btn btn-default">Submit</button> 
						  
						</form>
					
					</div>
					</div>
			
			</div>
		</div>
	</div>
		

	</div>

	<?php //include(D_TEMPLATE.'/footer.php'); ?>	
		
	<?php //if($debug == 1) { include('widgets/debug.php'); } ?>
		
</body>
	
</html>

**Comment by creptor** [comment]
html just phrase the code that is given, if they interfere the web browser will return an error or a weird looking page, but div tags don't affect the form tag.

maybe you should debug, has mentioned in the videos..... chrome tools let's you know what data is being sent to a page after a form is summited... just go to network (when on login.php) and press preserve log. This way you'll be able to find where is the problem.

Image  Example:
1. Go to the page, click menu >> more tools >> dev tools >> network, and check preserve log.
2. Check that the form method is post.
![2016-01-21 1](https://cloud.githubusercontent.com/assets/3092157/12490618/35d60f06-c055-11e5-9b18-65e12e330abb.png)
3. Click the submit button with the info you want to check.
4. The next thing that load should be the page redirected, with the information from the form, has the image shows.
![2016-01-21 2](https://cloud.githubusercontent.com/assets/3092157/12490712/b2517dc2-c055-11e5-824c-ece32f004223.png)
5. Check that the names are the same inside the script from the ones send, capital letter matter.
6. If this doesn't work please send the image of the data being sent, so I can help you further.
> To take screenshots use the key `imp pnt`

**Comment by JorgeBautista** [comment]
Don't know if I'm doing this right.
![caps_login_php](https://cloud.githubusercontent.com/assets/15808004/12518189/02bf5464-c105-11e5-9439-0b800e96af9f.jpg)
![caps_login_php1](https://cloud.githubusercontent.com/assets/15808004/12518196/133e360c-c105-11e5-820c-92cb6c798a25.jpg)

**Comment by creptor** [comment]
sry I didn't explain myself correctly. The thing is that you have to SUBMIT the form with an input, and then in the network look for the page redirecting (this case `login.php` because of the from action), and you should see the highlighted items I have in my picture :P

**Comment by creptor** [comment]
Check issue #159.
